=== MiguelCosta/EL-PED/logs/logs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="logs">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="log">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="username" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="date" type="xs:dateTime"/>
                            <xs:element name="action" type="xs:string"/>
                            <xs:element name="description" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MiguelCosta/EL-PED/logs/logs.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--<logs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="logs.xsd">-->
<logs>
    <log>
        <username>bruno</username>
        <name>Bruno</name>
        <date>2011-11-28T17:00:00</date>
        <action>SIP:ingestion</action>
        <description>Ingeriu um SIP</description>
    </log>
    <log>
        <username>miguel</username>
        <name>Miguel</name>
        <date>2011-11-28T17:30:00</date>
        <action>DIP:list</action>
        <description>Cenassa</description>
    </log>
    <log>
        <username>jcr</username>
        <name>Jose Carlos Ramalho</name>
        <date>2011-11-28T18:30:00</date>
        <action>DIP:View</action>
        <description>Projecto X visualizado</description>
    </log>
    <log>
        <username>jj</username>
        <name>JoseJoao</name>
        <date>2011-11-28T19:00:00</date>
        <action>SIP:Ingestion</action>
        <description>Ingestao</description>
    </log>
    <log>
        <username>vitor</username>
        <name>Vitor Costa</name>
        <date>2010-10-18T10:40:00</date>
        <action>DIP:Insert</action>
        <description>Inseriu projeto</description>
    </log>
</logs>
